setup:
  image: python:3.6
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install -r requirements.txt

production:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl -provider=heroku — app=impact-score — api-key=$HEROKU_API_KEY
  only:
    - main
